site_name: RT Corporation e-manual
theme: 
  name: material
  custom_dir: overrides
  logo: img/rt-logo-32x32.png
  favicon: img/rt-logo-32x32.png
  font: Incosolata
  palette:
    scheme: rt-red
  features:
    - navigation.expand

repo_url: https://github.com/rt-net/test-emanual
edit_uri: edit/main/docs/

site_url: https://rt-net.github.io/test-emanual/
copyright: Copyright &copy; 2020 RT Corporation
use_directory_urls: false # ディレクトリ名/index.htmlを開く

### 拡張設定 ###

extra:
  social:
     - icon: fontawesome/brands/twitter
       link: https://twitter.com/rt_corp
       name: 株式会社アールティTwitterアカウント
     - icon: fontawesome/brands/github
       link: https://github.com/rt-net
       name: 株式会社アールティGitHubページ
extra_css:
  - css/colors.css
  - css/style.css

plugins:
  - search
  - git-revision-date-localized
markdown_extensions:
  - attr_list  # 画像のalignを設定できる
  - pymdownx.tabbed  # タブで文章を切り替えられる
  - admonition  # Warningとかの飾り付けができる
  - pymdownx.highlight  # コードブロック用
  - pymdownx.superfences  # コードブロック用
  - pymdownx.emoji:  # アイコンが使える
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - CRANE+V2:
    - 製品について: cranev2/products.md
    - その他のコンテンツ: cranev2/others.md
  - CRANE-X7:
    - 製品について: crane-x7/products.md
    - その他のコンテンツ: crane-x7/others.md
  - Sciurus17:
    - 製品について: sciurus17/products.md
    - その他のコンテンツ: sciurus17/others.md
  - Raspberry Pi Mouse:
    - 1. 製品について: raspimouse/products.md
    - 2. デバイスドライバ:
      - 1. インストール: raspimouse/driver/install.md
      - 2. サンプルを動かす: raspimouse/driver/samples.md
    - 3. ROS:
      - 1. ROSパッケージのインストール: raspimouse/ros/install.md
      - 2. ROSサンプルの実行: raspimouse/ros/samples.md
      - 3. シミュレータの実行: raspimouse/ros/simulator.md
    - 4. ROS 2:
      - ROS 2パッケージのインストール: raspimouse/products.md
      - ROS 2サンプルの実行: raspimouse/products.md
    - 5. その他のコンテンツ: raspimouse/others.md
  - Jetson Nano Mouse:
    - 製品について: jnmouse/products.md
    - AIサンプル:
      - Jupyter Notebookのインストール: jnmouse/jupyter-notebook/install.md
      - Jupyter Notebookの実行: jnmouse/jupyter-notebook/example.md
    - その他のコンテンツ: jnmouse/others.md
  - トレーニングトレーサー:
    - 製品について: rt-tracer/products.md
    - その他のコンテンツ: rt-tracer/others.md
  - USB出力9軸IMUセンサモジュール: 
    - 製品について: usb9imu/products.md
    - その他のコンテンツ: usb9imu/others.md

