site_name: RT Corporation software e-manual
theme: 
  name: material
  custom_dir: overrides
  logo: img/rt-logo-32x32.png
  favicon: img/rt-logo-32x32.png
  font: Incosolata
  palette:
    scheme: rt-red
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top

repo_url: https://github.com/rt-net/e-manual
edit_uri: edit/main/docs/

site_url: https://rt-net.github.io/e-manual/
copyright: Copyright &copy; 2021 RT Corporation
use_directory_urls: false # ディレクトリ名/index.htmlを開く
site_description: 株式会社アールティのオンラインソフトウェアマニュアルです。製品をより便利に使うためのソフトウェアの使い方を紹介しています。

### 拡張設定 ###

extra:
  social:
     - icon: fontawesome/brands/twitter
       link: https://twitter.com/rt_corp
       name: 株式会社アールティTwitterアカウント
     - icon: fontawesome/brands/github
       link: https://github.com/rt-net
       name: 株式会社アールティGitHubページ
  analytics:
    provider: google
    property: UA-69742588-2

extra_css:
  - css/colors.css
  - css/style.css

plugins:
  - search:
      lang:
        - en
        - ja
  - redirects:  # リダイレクト用
      redirect_maps:
        cranev2/index.md: cranev2/products.md
        crane-x7/index.md: crane-x7/products.md
        sciurus17/index.md: sciurus17/products.md
        raspimouse/index.md: raspimouse/products.md
        jnmouse/index.md: jnmouse/products.md
        usb9imu/index.md: usb9imu/products.md

markdown_extensions:
  - attr_list  # 画像のalignを設定できる
  - pymdownx.tabbed  # タブで文章を切り替えられる
  - admonition  # Warningとかの飾り付けができる
  - pymdownx.highlight  # コードブロック用
  - pymdownx.superfences  # コードブロック用
  - pymdownx.emoji:  # アイコンが使える
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: 
    - トップページ: index.md
    - 本サイト内のコンテンツについて: about.md
  - CRANE+V2:
    - 1. 製品について: cranev2/products.md
    - 2. 参考リンク集: cranev2/others.md
  - CRANE-X7:
    - 1. 製品について: crane-x7/products.md
    - 2. 参考リンク集: crane-x7/others.md
  - Sciurus17:
    - 1. 製品について: sciurus17/products.md
    - 2. 参考リンク集: sciurus17/others.md
  - Raspberry Pi Mouse:
    - 1. 製品について: raspimouse/products.md
    - 2. デバイスドライバ:
      - 1. インストール: raspimouse/driver/install.md
      - 2. サンプルを動かす: raspimouse/driver/samples.md
    - 3. ROS / ROS 2:
      - 1. ROS / ROS 2パッケージのインストール: raspimouse/ros/install.md
      - 2. ROS / ROS 2サンプルの実行: raspimouse/ros/samples.md
      - 3. シミュレータの実行: raspimouse/ros/simulator.md
    - 4. 参考リンク集: raspimouse/others.md
  - Jetson Nano Mouse:
    - 1. 製品について: jnmouse/products.md
    # - AIサンプル:
    #   - Jupyter Notebookのインストール: jnmouse/jupyter-notebook/install.md
    #   - Jupyter Notebookの実行: jnmouse/jupyter-notebook/example.md
    - 2. 参考リンク集: jnmouse/others.md
  - トレーニングトレーサー:
    - 1. 製品について: rt-tracer/products.md
    - 2. 参考リンク集: rt-tracer/others.md
  - USB出力9軸IMUセンサモジュール: 
    - 1. 製品について: usb9imu/products.md
    - 2. 参考リンク集: usb9imu/others.md

